name: Pipeline - CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        
    - name: Install dependencies
      run: pip3 install -r requirements.txt
      
    - name: Test with unittest
      run:  python3 source/test_model.py
